<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Texts100 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            '1. Going to the Zoo',
            '2. Christmas Time',
            '3. She Goes to the Nurse',
            '4. Waiting',
            '5. Chores',
            '6. The First Song',
            '7. Visiting the Doctor',
            '8. Different Foods',
            '9. The Corner',
            '10. Surprise Party',
            '11. A New Pet',
            '12. Group Project',
            '13. A Cat and A Mouse',
            '14. Lemonade Stand',
            '15. New and Old',
            '16. The Kind Dentist',
            '17. A Trip to the Library',
            '18. A Lot of Ants',
            '19. Picking a Costume',
            '20. Petting Zoo',
            '21. Mom is Mad',
            '22. Father&rsquo;s Day',
            '23. The Baby Sister',
            '24. Sometimes You Lose',
            '25. A New Home',
            '26. Chris and His Fish',
            '27. The Oldest Brother',
            '28. A Successful Trade',
            '29. Making a Snowman',
            '30. English Skills',
            '31. Practicing Drawing',
            '32. A Day for Ice Cream',
            '33. Taking Tests',
            '34. Helen is Busy',
            '35. Messing Up',
            '36. Introducing Myself',
            '37. A Long Wait',
            '38. The Teacher Takes Away His Phone',
            '39. No One Likes the Flu',
            '40. The Circus',
            '41. An Unhealthy Boy',
            '42. Ferris Wheel',
            '43. More Money',
            '44. Loving Dance',
            '45. A Fun Sleepover',
            '46. Apology',
            '47. Glass of Milk on the Desk',
            '48. A Simple Gift',
            '49. Hide-and-Seek',
            '50. Excited for the Mail',
            '51. Having Fun on a Swing',
            '52. He Walks His Dogs',
            '53. A Pencil for Everything',
            '54. Being Careless',
            '55. Fluffy the Rabbit',
            '56. Three Friends and a Jump Rope',
            '57. He Plays with the Ladybug&nbsp',
            '58. The Dog That Digs',
            '59. Playing with the Monkey Bars&nbsp',
            '60. Playing a Doctor',
            '61. Art Class',
            '62. Getting Ready for Soccer Practice',
            '63. The Pouch of a Kangaroo',
            '64. Aunt and Uncle',
            '65. A Busy Boy',
            '66. Fruit Salad',
            '67. He Takes His Test',
            '68. Parent-teacher Conference',
            '69. The Second Dog',
            '70. A Cat and a Ball of Yarn',
            '71. Taking Care of His Orange Tree',
            '72. The Missing Notebook',
            '73. Tag, You&rsquo;re It!',
            '74. Different Flavors',
            '75. Daydreaming at School',
            '76. A Pet for Dad',
            '77. Too Sick',
            '78. The Worst Student',
            '79. Bad Manners',
            '80. Transferring to Another Class',
            '81. Good Manners',
            '82. The Trouble with Braces',
            '83. Lost on the First Day',
            '84. Stealing is Bad',
            '85. Picking Her Up',
            '86. Saving the Princess',
            '87. Make It Hot, Make It Cold',
            '88. A Good Shower',
            '89. The Wrong Color',
            '90. Forgetting Her Glasses',
            '91. Quitting His Job',
            '92. Future Goals',
            '93. A Kind Stranger',
            '94. Excited for Thanksgiving',
            '95. A Sad Book and a Happy Book',
            '96. The Water Slide at the Amusement Park',
            '97. Keeping a Diary',
            '98. Trying on Shoes',
            '99. A Lot of Pants',
            '100. Chili Sauce Lover',
        ];

        foreach ($names as $key => $name) {
            DB::table('one_hundred_texts')->insert([
                'order' => $key+1,
                'name' => $name,
                'slug' => Str::slug($name),
                'link' => "https://www.eslfast.com/kidsenglish/ke/ke". str_pad($key+1 , 3 , '0' , STR_PAD_LEFT) .".htm"
            ]);
        }
    }

//    public function num($num)
//    {
//      if ($num < 10) return '00' . $num;
//      if ($num >= 10 && $num < 100) return '0' . $num;
//      if ($num >= 100) return $num;
//    }

    /*
     '18. A Lot of Ants',
    '19. Picking a Costume',
    '20. Petting Zoo',
    '21. Mom is Mad',
    '22. Father&rsquo;s Day',
    '23. The Baby Sister',
    '24. Sometimes You Lose',
    '25. A New Home',
    '26. Chris and His Fish',
    '27. The Oldest Brother',
    '28. A Successful Trade',
    '29. Making a Snowman',
    '30. English Skills',
    '31. Practicing Drawing',
    '32. A Day for Ice Cream',
    '33. Taking Tests',
    '34. Helen is Busy',
'35. Messing Up',
    '36. Introducing Myself',
'37. A Long Wait',
'38. The Teacher Takes Away His Phone',
'39. No One Likes the Flu',
'40. The Circus',
'41. An Unhealthy Boy',
'42. Ferris Wheel',
'43. More Money',
'44. Loving Dance',
'45. A Fun Sleepover',
'46. Apology',
'47. Glass of Milk on the Desk',
'48. A Simple Gift',
'49. Hide-and-Seek',
'50. Excited for the Mail',
'51. Having Fun on a Swing',
'52. He Walks His Dogs',
'53. A Pencil for Everything',
'54. Being Careless',
'55. Fluffy the Rabbit',
'56. Three Friends and a Jump Rope',
'57. He Plays with the Ladybug&nbsp',
'58. The Dog That Digs',
'59. Playing with the Monkey Bars&nbsp',
'60. Playing a Doctor',
'61. Art Class',
'62. Getting Ready for Soccer Practice',
'63. The Pouch of a Kangaroo',
'64. Aunt and Uncle',
'65. A Busy Boy',
'66. Fruit Salad',
'67. He Takes His Test',
'68. Parent-teacher Conference',
'69. The Second Dog',
'70. A Cat and a Ball of Yarn',
'71. Taking Care of His Orange Tree',
'72. The Missing Notebook',
'73. Tag, You&rsquo;re It!',
'74. Different Flavors',
'75. Daydreaming at School',
'76. A Pet for Dad',
'77. Too Sick',
'78. The Worst Student',
'79. Bad Manners',
'80. Transferring to Another Class',
'81. Good Manners',
'82. The Trouble with Braces',
'83. Lost on the First Day',
'84. Stealing is Bad',
'85. Picking Her Up',
'86. Saving the Princess',
'87. Make It Hot, Make It Cold',
'88. A Good Shower',
'89. The Wrong Color',
'90. Forgetting Her Glasses',
'91. Quitting His Job',
'92. Future Goals',
'93. A Kind Stranger',
'94. Excited for Thanksgiving',
'95. A Sad Book and a Happy Book',
'96. The Water Slide at the Amusement Park',
'97. Keeping a Diary',
'98. Trying on Shoes',
'99. A Lot of Pants',
'100. Chili Sauce Lover',
     */
}
